In [75]:
import numpy as np

Hari ini belajar mengenai Numpy

In [76]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [77]:
a.shape

(3,)

In [78]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


dari data a yaitu [1,2,3],
dapat diketahui bahwa dimensi nya 1

In [79]:
# Get Dimension
a.ndim

1

dari data b yaitu 
    [[9. 8. 7.]
     [6. 5. 4.]],
dapat diketahui bahwa shape nya yaitu (2, 3) dengan keterangan 2 baris dan 3 kolom

In [80]:
b.shape

(2, 3)

serta dapat diketahui bahwa dimensi dari b yaitu 2, dengan keterangan:
    sebelum akhirnya terdapat elemen angka terdapat 2 kurung siku

In [81]:
b.ndim

2

jika suatu array bersifat 1 dimensi (1D), shape nya menghasilkan jumlah elemen dari array tersebut

In [82]:
a, a.ndim, a.shape

(array([1, 2, 3]), 1, (3,))

sedangkan jika arraynya bersifat 2 dimensi (2D), shape nya menghasilkan jumlah kolom dan baris dari array tersebut

In [83]:
b, b.ndim, b.shape

(array([[9., 8., 7.],
        [6., 5., 4.]]),
 2,
 (2, 3))

In [84]:
y = np.zeros((3))

In [85]:
y

array([0., 0., 0.])

In [86]:
y.ndim

1

In [87]:
y.shape

(3,)

In [88]:
arr = np.array([
                 [1, 2, 3, 4], 
                 [5, 6, 7, 8],
                 [6, 5, 6, 7]
               ])

In [89]:
arr.shape

(3, 4)

In [90]:
arr.ndim

2

In [91]:
three_dim_array = np.array([[[1, 2, 3],
                             [4, 5, 6],
                             [7, 8, 9]],

                            [[10, 11, 12],
                             [13, 14, 15],
                             [16, 17, 18]],

                            [[19, 20, 21],
                             [22, 23, 24],
                             [25, 26, 27]]])


In [92]:
three_dim_array.shape

(3, 3, 3)

In [93]:
three_dim_array.ndim

3

In [94]:
c = np.array([1,2,3,4,5])

In [95]:
c.shape

(5,)

In [96]:
d = np.array([[3,5,6],
              [4,1,9],
              [7,4,9]
             ])

In [97]:
d.ndim

2

In [98]:
d.shape

(3, 3)

In [99]:
e = np.array([[3,5,7], [5,6,1]])

In [100]:
e.shape

(2, 3)

In [101]:
e.ndim

2

In [122]:
z = np.zeros((3,4,5)) # 3 merupakan jumlah blok, 4 merupakan jumlah baris, dan 5 merupakan jumlah kolom

In [103]:
z

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [104]:
z.shape

(3, 4, 5)

In [105]:
z.ndim

3

In [121]:
x = np.zeros((2,4,5)) # 2 merupakan jumlah blok, 4 merupakan jumlah baris, dan 5 merupakan jumlah kolom

In [117]:
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [120]:
i = np.zeros((1,3,4)) # 1 merupakan jumlah blok, 3 merupakan jumlah baris, dan 4 merupakan jumlah kolom

In [119]:
i

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [110]:
a

array([1, 2, 3])

In [111]:
a.dtype

dtype('int64')

kita juga dapat menentukan tipe data yang diinginkan dalam pembuatan array

In [112]:
a = np.array([1,2,3], dtype='int16')

dibawah ini merupakan cara mengetahui tipe data dari variabel numpy yang telah dibuat

In [113]:
a.dtype

dtype('int16')

itemsize(), nbytes(), size() pada numpy python

itemsize() digunakan untuk menghitung konsumsi "bytes" per elemen dalam sebuah variabel numpy,
    sedangkan nbytes() digunakan untuk menghitung total konsumsi "bytes" keseluruhan (seluruh data) dalam sebuah variabel numpy

dimana 1 bytes terdiri dari 8 bit, dan 1 bit berisi antara angka biner (0 atau 1)

    serta, size() digunakan untuk mengetahui jumlah total elemen dalam sebuah array / variabel numpy

In [8]:
import numpy as np

a = np.array([[1,2,3], [4,5,6]], dtype='int16')
print("nbytes dari a:", a.nbytes)
print("item size dari a:", a.itemsize)
print("size dari a:", a.size, "\n")

b = np.array([[3,4,5], [7,8,9]], dtype='int8')
print("nbytes dari b:", b.nbytes)
print("item size dari b:", b.itemsize)
print("size dari b:", b.size)

nbytes dari a: 12
item size dari a: 2
size dari a: 6 

nbytes dari b: 6
item size dari b: 1
size dari b: 6


berikut merupakan cara mengakses elemen, baris, atau kolom tertentu dalam array / variabel numpy

In [10]:
b = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [14]:
# akses elemen tertentu
print(b[1, -2])
print(b[0, -1])
print(b[1, 5])

11
6
12


In [17]:
# akses baris tertentu 
print(b[0])
print(b[1])

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


In [44]:
# akses kolom tertentu 
print(b[:, 1])
print(b[:, -1])
print(b[:, 0], "\n")

# semisal kita ingin mengakses data kelipatan 2 dari baris ke 2 dari variabel b, maka caranya:
print(b)
print("data angka kelipatan 2 dari baris ke 2:",b[1, 1:12:2])
        # pada parameter ke 2, angka 1 menunjukkan data awal yang diinginkan, angka 12 menunjukkan data terakhir 
            # yang diinginkan, serta angka 2 menunjukkan kelipatan 2 

# semisal kita ingin mengakses data angka ganjil dari baris ke 1 dari variabel b, maka caranya:
print("data angka ganjil dari baris ke 1:", b[0, 0:5:2])

[2 8]
[ 6 12]
[1 7] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
data angka kelipatan 2 dari baris ke 2: [ 8 10 12]
data angka ganjil dari baris ke 1: [1 3 5]


In [57]:
# cara untuk mengubah suatu elemen dalam array menjadi yang diinginkan
c = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
c[0, -1] = 20
print(c, "\n")

d = c
d[:, 2] = [7,17]
print(d)

[[ 1  2  3  4  5 20]
 [ 7  8  9 10 11 12]] 

[[ 1  2  7  4  5 20]
 [ 7  8 17 10 11 12]]


In [62]:
# berikut cara untuk mengakses suatu elemen dalam array numpy bersifat 3 dimensi (3D)
y = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(y)

print(y[1,0,1])
print(y[0,1,0])


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
6
3


In [18]:
# berikut cara untuk mengakses baris ke 1 dan ke 2 pada kedua blok dalam array 3D
import numpy as np

y = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(y, "\n")

print("baris ke 1 pada kedua blok:", y[:,0]) # ":" berarti menunjukkan seluruh data pada baris tersebut
print("baris ke 2 pada kedua blok:", y[:,1], "\n") # ":" berarti menunjukkan seluruh data pada baris tersebut

a = y[:,1] = [[6,4],[1,7]] # cara untuk mengubah elemen pada baris yang diinginkan
print(y)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

baris ke 1 pada kedua blok: [[1 2]
 [5 6]]
baris ke 2 pada kedua blok: [[3 4]
 [7 8]] 

[[[1 2]
  [6 4]]

 [[5 6]
  [1 7]]]


In [25]:
# berikut cara untuk membuat array berisi angka yang diinginkan dengan shape dan tipe yang telah ditentukan
r = np.full((2,3), 56) # 56 merupakan yang diinginkan
print(r, "\n") 

c = np.full((1,4,2), 21, dtype='int16') # 21 merupakan yang diinginkan
print(c)

[[56 56 56]
 [56 56 56]] 

[[[21 21]
  [21 21]
  [21 21]
  [21 21]]]


mempelajari np.identity() pada numpy python
np.identity: fungsi untuk membuat matriks identitas.
    Matriks identitas adalah matriks persegi yang angka 1 diagonalnya dari kiri atas ke kanan bawah dan nol di tempat lain.

In [30]:
b = np.identity(5) # 5 mengindikasikan jumlah baris dan kolom (RC, row column)
print(b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


mempelajari cara mengulangi sebuah array menjadi jumlah yang diinginkan

In [35]:
i = np.array([[3,4,5]])
x = np.repeat(i, 4, axis=0) # 4 merupakan jumlah pengulangan yang diinginkan
print(x) 

[[3 4 5]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


implementasi dasar matematika dalam numpy python

In [42]:
a = np.array([2,3,4,5])
print(a + 2)
print(a - 2)
print(a / 2)
print(a ** 2, "\n")

# dapat juga dilakukan dengan metode antar array 
b = np.array([1,2,3,4])
print(a + b)
print(a - b)
print(a ** b, "\n")

# trigonometri
c = np.array([4,5,6,7])
print(np.sin(c))
print(np.cos(c))
print(np.tan(c))

[4 5 6 7]
[0 1 2 3]
[1.  1.5 2.  2.5]
[ 4  9 16 25] 

[3 5 7 9]
[1 1 1 1]
[  2   9  64 625] 

[-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
[-0.65364362  0.28366219  0.96017029  0.75390225]
[ 1.15782128 -3.38051501 -0.29100619  0.87144798]


mempelajari implementasi linear algebra pada numpy python (matmul() dan dot())

In [7]:
import numpy as np

a = np.array([[1,2],[3,4]])
print(a, "\n")

b = np.array([[5,6],[7,8]])
print(b)

np.matmul(a, b) # matmul = matrix multiplication
# [1*5 + 2*7] = [19]
# [1*6 + 2*8] = [22]

# [3*5 + 4*7] = [43]
# [3*6 + 4*8] = [50]

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [11]:
c = np.array([[3,5],[6,8]])
print(c, "\n")

d = np.array([[2,4],[5,7]])
print(d)

np.matmul(c, d)
# [3*2 + 5*5] = [31]
# [3*4 + 5*7] = [47]

# [6*2 + 8*5] = [52]
# [6*4 + 8*7] = [80]

[[3 5]
 [6 8]] 

[[2 4]
 [5 7]]


array([[31, 47],
       [52, 80]])

In [13]:
i = np.array([5,6,7])
v = np.array([3,2,5])
np.dot(i,v) # 5*3 + 6*2 + 7*5 = 62

np.int64(62)

mencari determinan dari sebuah identitas matriks

In [12]:
i = np.identity(4)
np.linalg.det(i) # determinan dari matriks identitas bernilai 1 

np.float64(1.0)

mempelajari statistik pada numpy python

In [21]:
stats = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(stats)

print(np.min(stats)) # data terkecil dari seluruh baris 
print(np.max(stats)) # data terbesar dari seluruh baris

print(np.min(stats, axis=1)) # data terkecil dari tiap baris
print(np.max(stats, axis=1)) # data terbesar dari tiap baris

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
2
10
[2 5 8]
[ 4  7 10]


mempelajari reshape() dan transpose() pada numpy python
    reshape() digunakan untuk mengubah bentuk arrray, sedangkan
        transpose() digunakan untuk membalik posisi array

In [31]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before, "\n")

# reshape()
after = before.reshape((4,2))
after1 = before.reshape((2,2,2))
print("reshape:")
print(after)
print(after1, "\n")

# transpose()
after2 = before.transpose()
print("transpose:")
print(after2)

[[1 2 3 4]
 [5 6 7 8]] 

reshape:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

transpose:
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


penumpukan vertikal array pada numpy python (menggunakan vstack())

In [34]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

a = np.vstack([v1,v2])
b = np.vstack([v1,v2,v1,v2])
print(a, "\n")
print(b)

[[1 2 3 4]
 [5 6 7 8]] 

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


penumpukan horizontal array pada numpy python (menggunakan hstack())

In [39]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1)
print(h2, "\n")

print("result:")
print(np.hstack((h1,h2)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]] 

result:
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]
