In [75]:
import numpy as np

Hari ini belajar mengenai Numpy

In [76]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [77]:
a.shape

(3,)

In [78]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


dari data a yaitu [1,2,3],
dapat diketahui bahwa dimensi nya 1

In [79]:
# Get Dimension
a.ndim

1

dari data b yaitu 
    [[9. 8. 7.]
     [6. 5. 4.]],
dapat diketahui bahwa shape nya yaitu (2, 3) dengan keterangan 2 baris dan 3 kolom

In [80]:
b.shape

(2, 3)

serta dapat diketahui bahwa dimensi dari b yaitu 2, dengan keterangan:
    sebelum akhirnya terdapat elemen angka terdapat 2 kurung siku

In [81]:
b.ndim

2

jika suatu array bersifat 1 dimensi (1D), shape nya menghasilkan jumlah elemen dari array tersebut

In [82]:
a, a.ndim, a.shape

(array([1, 2, 3]), 1, (3,))

sedangkan jika arraynya bersifat 2 dimensi (2D), shape nya menghasilkan jumlah kolom dan baris dari array tersebut

In [83]:
b, b.ndim, b.shape

(array([[9., 8., 7.],
        [6., 5., 4.]]),
 2,
 (2, 3))

In [84]:
y = np.zeros((3))

In [85]:
y

array([0., 0., 0.])

In [86]:
y.ndim

1

In [87]:
y.shape

(3,)

In [88]:
arr = np.array([
                 [1, 2, 3, 4], 
                 [5, 6, 7, 8],
                 [6, 5, 6, 7]
               ])

In [89]:
arr.shape

(3, 4)

In [90]:
arr.ndim

2

In [91]:
three_dim_array = np.array([[[1, 2, 3],
                             [4, 5, 6],
                             [7, 8, 9]],

                            [[10, 11, 12],
                             [13, 14, 15],
                             [16, 17, 18]],

                            [[19, 20, 21],
                             [22, 23, 24],
                             [25, 26, 27]]])


In [92]:
three_dim_array.shape

(3, 3, 3)

In [93]:
three_dim_array.ndim

3

In [94]:
c = np.array([1,2,3,4,5])

In [95]:
c.shape

(5,)

In [96]:
d = np.array([[3,5,6],
              [4,1,9],
              [7,4,9]
             ])

In [97]:
d.ndim

2

In [98]:
d.shape

(3, 3)

In [99]:
e = np.array([[3,5,7], [5,6,1]])

In [100]:
e.shape

(2, 3)

In [101]:
e.ndim

2

In [122]:
z = np.zeros((3,4,5)) # 3 merupakan jumlah blok, 4 merupakan jumlah baris, dan 5 merupakan jumlah kolom

In [103]:
z

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [104]:
z.shape

(3, 4, 5)

In [105]:
z.ndim

3

In [121]:
x = np.zeros((2,4,5)) # 2 merupakan jumlah blok, 4 merupakan jumlah baris, dan 5 merupakan jumlah kolom

In [117]:
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [120]:
i = np.zeros((1,3,4)) # 1 merupakan jumlah blok, 3 merupakan jumlah baris, dan 4 merupakan jumlah kolom

In [119]:
i

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [110]:
a

array([1, 2, 3])

In [111]:
a.dtype

dtype('int64')

kita juga dapat menentukan tipe data yang diinginkan dalam pembuatan array

In [112]:
a = np.array([1,2,3], dtype='int16')

dibawah ini merupakan cara mengetahui tipe data dari variabel numpy yang telah dibuat

In [113]:
a.dtype

dtype('int16')